def generate_report(email_data, headers, ip_info, reputation):
    report = []
    report.append("="*50)
    report.append("EMAIL ANALYSIS REPORT")
    report.append("="*50)
    report.append(f"From: {email_data.get('from')}")
    report.append(f"Reply-To: {email_data.get('reply_to')}")
    report.append(f"Subject: {email_data.get('subject')}")
    report.append(f"Date: {email_data.get('date')}")
    report.append(f"Sender IP: {email_data.get('sender_ip')}")
    report.append("\n--- HEADER CHECKS ---")
    report.append(f"SPF Record: {headers.get('spf')}")
    report.append(f"DMARC Record: {headers.get('dmarc')}")
    report.append(f"DKIM Present: {headers.get('dkim_present')}")
    report.append(f"Reply-To Mismatch: {headers.get('reply_to_mismatch')}")
    report.append("\n--- IP GEOLOCATION ---")
    report.append(f"Country: {ip_info.get('country')}")
    report.append(f"ISP: {ip_info.get('isp')}")
    report.append(f"Org: {ip_info.get('org')}")
    report.append("\n--- REPUTATION ---")
    report.append(f"VirusTotal: {reputation.get('virustotal_ip')}")
    report.append(f"AbuseIPDB Score: {reputation.get('abuseipdb', {}).get('abuseConfidenceScore')}")
    report.append("="*50)
    return "\n".join(report)
